language: c

# Enable when packages are whitelisted

#sudo: false
#
#addons:
#  apt:
#    packages:
#    - bc
#    - libkqueue0
#    - libkqueue-dee

before_install:
- sudo apt-get update -qq
- sudo apt-get install bc libkqueue-dev libkqueue0 git autoconf libcurl4-openssl-dev automake libtool -qq

script:
- make
- make check
