.\"
.\" Copyright (c) 2018 Mark Heily <mark@heily.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd August 5, 2018
.Dt JOB 8
.Os
.Sh NAME
.Nm job
.Nd job configuration file
.\" .Sh SYNOPSIS
.\" .Nm ???what to put here???
.Sh DESCRIPTION
The 
.Nm
configuration file format is a TOML document with the following
fields:
.Bl -column "EnvironmentVariables" "dictionary" "Description"
.It Sy Name Ta Sy Type Ta Sy Description
.It After Ta array Ta "Jobs that this job must run after."
.It Before Ta array Ta "Jobs that this job must run before."
.It Description Ta string Ta "A multi-line description of the job."
.It Enable Ta boolean Ta "Whether to enable the job."
.It EnvironmentVariables Ta dictionary Ta "Environment variable key/value pairs"
.It Group Ta string Ta "The group name for setgid(2)"
.It InitGroups Ta boolean Ta "Whether to call initgroups(3)"
.It KeepAlive Ta boolean Ta "Whether to restart the job if it exits"
.It Program Ta array Ta "The program to execute"
.It RootDirectory Ta string Ta "The directory to chroot(2) into"
.It StandardErrorPath Ta string Ta "The path to redirect STDERR into"
.It StandardInPath Ta string Ta "The path to redirect STDIN into"
.It StandardOutPath Ta string Ta "The path to redirect STDOUT into"
.It Title Ta string Ta "A one-line title to display"
.It Umask Ta string Ta "An octal value for umask(2)"
.It User Ta string Ta "The username for setuid(2)"
.It WorkingDirectory Ta string Ta "The path to set via chdir(2)"

.El
.Sh FILES
.Bl -tag -width "/etc/job.d/*XXXX" -compact
.It Pa /etc/job.d/*
The directory containing all enabled jobs.
.El
.\" .Sh ERRORS
.Sh SEE ALSO
.Xr job 8
.Xr jobd 8
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
