#!/bin/sh
#
# Copyright (c) 2015 Mark Heily <mark@heily.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

if [ `whoami` = 'root' ] ; then
	if [ -d /var/db ] ; then
		pkgdatadir="/var/db/launchd"
	else
		pkgdatadir="/var/lib/launchd"
	fi
	pidfile="/var/run/launchd.pid"
	agentdir="/usr/local/etc/launchd/agents"
	daemondir="/usr/local/etc/launchd/daemons"
else
	pkgdatadir="$HOME/.launchd/run"
	pidfile="$pkgdatadir/launchd.pid"
	agentdir="$HOME/.launchd/agents"
	daemondir="" # N/A
fi
watchdir="$pkgdatadir/new"

command=$1
shift

case $command in
load)
	for path in $* ; do
		if [ -d $path ] ; then
			cp -R $path/*.json $watchdir
		else
			cp $path $watchdir
		fi
	done
	kill -HUP `cat $pidfile`
	;;

unload)
	filespec=`find $* -name '*.json'`
	for path in $filespec ; do
		label=`basename "$path" | sed 's/\.json$//'`
		touch $watchdir/$label.unload
	done
	kill -HUP `cat $pidfile`
	;;


install)
	filespec=`find $* -name '*.json'`
	for path in $filespec ; do
		label=`basename "$path" | sed 's/\.json$//'`
		cp $path $watchdir/$label.install
	done
	kill -HUP `cat $pidfile`
	;;

uninstall)
	echo "XXX - STUB"
	exit 1
	;;

list)
	listfile="$pkgdatadir/launchctl.list"
	rm -f $listfile
	kill -USR1 `cat $pidfile`
	while [ ! -f $listfile ] ; do sleep 0.2 ; done
	cat $listfile
	;;

*)
	echo "invalid command"
	exit 1
esac

exit 0
