.TH "JOBD" "8" "May 29, 2016" "FreeBSD 11.0-CURRENTMAR2016" "FreeBSD System Manager's Manual"
.nh
.if n .ad l
.SH "NAME"
\fBjobd\fR
\- job management daemon
.SH "SYNOPSIS"
.HP 5n
\fBjobd\fR
[\fI-f\fR]
[\fI-v\fR]
.SH "DESCRIPTION"
\fBjobd\fR
manages jobs that are defined in configuration files
located under
\fI/usr/local/etc/job.d\fR.
The format of job
configuration files is described in
job(5).
.PP
When a new job configuration file is created,
\fBjobd\fR
will automatically detect this and load the job into memory. By default,
the job will be disabled. To enable the job, the
\fBjobctl enable\fR
command should be executed.
.PP
When an existing job configuration file is deleted,
\fBjobd\fR
will automatically detect this and remove the job from memory. If the job
is currently running, it will be stopped.
.PP
When an existing configuration file is modified,
\fBjobd\fR
will automatically detect this and transition the job into the "refresh-needed" state.
This alerts the system administrator that the job is running, but with an outdated configuration. is outdated
and needs to be refreshed. To refresh the job, the
\fBjobctl refresh\fR
command should be executed.
.SH "OPTIONS"
The following options are available:
.TP 8n
-f
Do not become a daemon.
.TP 8n
-v
Increase the logging verbosity.
.SH "ENVIRONMENT"
When running under a debugger, it is useful to prevent
\fBjobd\fR
from calling fork(2). This can be done by setting the JOBD_DEBUG_NOFORK environment variable to any non-empty string.
.SH "FILES"
.TP 8n
/usr/local/etc/job.d
Directory where job manifests are stored.
.SH "EXIT STATUS"
The
\fBjobd\fR
command exits\[u00A0]0 on success, and\[u00A0]>0 if an error occurs
.SH "SEE ALSO"
jobcfg(1)
jobctl(1)
job(5)
.SH "AUTHORS"
Mark Heily <mark@heily.com>
