#!/bin/sh
#
# Copyright (c) 2016 Mark Heily <mark@heily.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

if [ `id -u` -eq 0 ] ; then
	databasedir="/var/db/launchd/cfg"
else
	databasedir="$HOME/.launchd/cfg"
fi

command=$1
shift

case $command in
get)
	echo "ERROR"
	;;

set)
	echo "ERROR"
	;;

list)
	cd $databasedir 
	for key in * ; do 
		printf "%s=\"%s\"\n" "$key" "$(cat $key)"
	done
	;;

*)
	echo "invalid command"
	exit 1
esac

exit 0
